### ISSUE TITLE
GOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE is not defined

### ISSUE THREAD

**Issue by joelspadin** [protocolbuffers/protobuf#10108]
**What version of protobuf and what language are you using?**
Version: v3.21.1
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Windows 10.0.19042

**What runtime / compiler are you using (e.g., python version or gcc version)**
armclang 6.15

**What did you do?**
I am trying to build protobuf for an application which uses the armclang compiler. I have gotten it working, but there is one case where I'm not sure if I have run into a bug in the upstream code or just something I need to patch locally for my environment. Compiling a file that `#include`s a generated .pb.h file with `-Werror -Wundef` results in this error:

> google/protobuf/inlined_string_field.h:430:5: error: 'GOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE' is not defined, evaluates to 0 [-Werror,-Wundef]

https://github.com/protocolbuffers/protobuf/blob/3380463ff87873b1ed07b730c79d78477289d0cd/src/google/protobuf/inlined_string_field.h#L430

There are no other references to `GOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE` in the codebase. Is this old code that is now unused, or is this a config flag you can pass on the command line? Should the code should be using `#ifdef` instead?

**Comment by jorgbrown** [comment]
Fixed in https://github.com/protocolbuffers/protobuf/commit/d37cbfd4485f22372d9f054d100e65e41fbea628

**Comment by joelspadin** [comment]
Thanks!

**Comment by MoodieG** [comment]
@jorgbrown This fix is checked in on Jun 13th but is still not available in the latest releases. Any idea when a release will include this fix?
