### ISSUE TITLE
Degrade from 3.4 to 3.5: Windows Protobuf Compiler does no longer understand * operator for multiple input files

### ISSUE THREAD

**Issue by apacha** [protocolbuffers/protobuf#3957]
I tried to follow the instructions from [tensorflow-models repo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) up until the point where to run 

`protoc object_detection/protos/*.proto --python_out=.`

So I downloaded the appropriate Windows version and added it to my Path. But when running the corresponding windows command: 

`protoc .\object_detection\protos\*.proto --python_out=.`
or even with the forward slash
`protoc object_detection/protos/*.proto --python_out=.`

I only get the error `object_detection/protos/*.proto: No such file or directory`, indicating that it does not understand the *-operator. When compiling the files individually that reside in that directory, it works as expected.

**Comment by pherl** [comment]
@laszlocsomor I suspect this has something to do with the long path support.

**Comment by laszlocsomor** [comment]
I suspect this never worked on Windows.

On Linux, Bash expands the wildcards so the main method's argv already contains the list of files, not the wildcard.

**Comment by apacha** [comment]
@laszlocsomor Very likely, this behavior never worked, but it would be nice, if it did work.

**Comment by laszlocsomor** [comment]
I have a fix for it. Stay tuned.

**Comment by Aisuko** [comment]
I have the same issue on my win10 and anaconda3 , with the instructions from tensorflow-models repo up until the point where to run

     protoc object_detection/protos/*.proto --python_out=.

![2](https://user-images.githubusercontent.com/8053949/33983381-f8acc1d0-e0ee-11e7-8128-46f41057e1d8.JPG)

**Comment by apacha** [comment]
There is a nice script here that you can use instead: https://github.com/tensorflow/models/issues/1934

**Comment by Aisuko** [comment]
Thanks 😘  @apacha 
This my solution:

Head to the [protoc releases page](https://github.com/google/protobuf/releases) and download the protoc-3.4.0-win32.zip, extract it, and you will find protoc.exe in the bin directory.

Move this to models/research folder clone to local [tensorflow model project](https://github.com/tensorflow/models/) 

Next,you can use the protoc command like
    
    protoc object_detection/protos/*.proto --python_out=.


[Reference linking](https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/)

**Comment by apacha** [comment]
@Aisuko What are you talking about? You are describing exactly what I've tried and failed with. Using the *-operator on Windows does not work with Version 3.4.0 of protoc.

**Comment by Aisuko** [comment]
@apacha  I think that i have been successed.
![1](https://user-images.githubusercontent.com/8053949/34135322-e924ed46-e49a-11e7-8cdc-f683248c44df.JPG)

**Comment by apacha** [comment]
@Aisuko You're right. This actually works in Version 3.4.0 of protoc but not with version 3.5.0 and is therefore a degrade of the Windows protoc.exe.

**Comment by acozzette** [comment]
@pherl What's the current status of this issue? Is this now fixed on master?

**Comment by pherl** [comment]
My understanding we probably would have to build the protoc directly using mingw in windows without using cross-compile. I will see if we can fix this in 3.6

**Comment by jeffreytang** [comment]
Just tried latest 3.6.0 on Windows 10 command window, still could not recognize "*.proto"

**Comment by vthoppae** [comment]
Using batch file try this option using for loop command
for /f %%G IN ('dir /b "C:\Protobuf\protoc-3.6.0\in\*.proto"') do (
protoc --proto_path=C:\Protobuf\protoc-3.6.0\in --java_out=C:\Protobuf\protoc-3.6.0\out %%G
)

**Comment by moshebitan** [comment]
This is one liner to replace google command for compliing proto files.
ORIGINAl (Doesn't work on windows): 
protoc object_detection\protos\*.proto --python_out=.

Batch version **works** on windows:
for /f %G in ('dir /b object_detection\protos\*.proto') do protoc object_detection\protos\%G --python_out=.

**Comment by laszlocsomor** [comment]
I fixed this, and it works with long paths too:

1. In MSYS:
    ```
    $ find /c/tmp/proto/aaaaaaaa.aaa/ -name '*.proto' -type f
    /c/tmp/proto/aaaaaaaa.aaa/bbbbbbbb.bbb/cccccccc.ccc/dddddddd.ddd/eeeeeeee.eee/ffffffff.fff/gggggggg.ggg/hhhhhhhh.hhh/iiiiiiii.iii/jjjjjjjj.jjj/kkkkkkkk.kkk/llllllll.lll/mmmmmmmm.mmm/nnnnnnnn.nnn/oooooooo.ooo/pppppppp.ppp/qqqqqqqq.qqq/rrrrrrrr.rrr/ssssssss.sss/tttttttt.ttt/uuuuuuuu.uuu/vvvvvvvv.vvv/wwwwwwww.www/a.proto
    /c/tmp/proto/aaaaaaaa.aaa/bbbbbbbb.bbb/cccccccc.ccc/dddddddd.ddd/eeeeeeee.eee/ffffffff.fff/gggggggg.ggg/hhhhhhhh.hhh/iiiiiiii.iii/jjjjjjjj.jjj/kkkkkkkk.kkk/llllllll.lll/mmmmmmmm.mmm/nnnnnnnn.nnn/oooooooo.ooo/pppppppp.ppp/qqqqqqqq.qqq/rrrrrrrr.rrr/ssssssss.sss/tttttttt.ttt/uuuuuuuu.uuu/vvvvvvvv.vvv/wwwwwwww.www/b.proto

    $ find /c/tmp/proto/aaaaaaaa.aaa/ -name '*.h' -type f | wc -l
    0
    ```

2. In cmd.exe:
    ```
    c:\>cd c:\tmp\proto

    c:\tmp\proto>protoc-dev.exe aaaaaaaa.aaa\bbbbbbbb.bbb\cccccccc.ccc\dddddddd.ddd\eeeeeeee.eee\ffffffff.fff\gggggggg.ggg\hhhhhhhh.hhh\iiiiiiii.iii\jjjjjjjj.jjj\kkkkkkkk.kkk\llllllll.lll\mmmmmmmm.mmm\nnnnnnnn.nnn\oooooooo.ooo\pppppppp.ppp\qqqqqqqq.qqq\rrrrrrrr.rrr\ssssssss.sss\tttttttt.ttt\uuuuuuuu.uuu\vvvvvvvv.vvv\wwwwwwww.www\*.proto --cpp_out=.
    ```

3. In MSYS:
    ```
        $ find /c/tmp/proto/aaaaaaaa.aaa/ -name '*.h' -type f
    /c/tmp/proto/aaaaaaaa.aaa/bbbbbbbb.bbb/cccccccc.ccc/dddddddd.ddd/eeeeeeee.eee/ffffffff.fff/gggggggg.ggg/hhhhhhhh.hhh/iiiiiiii.iii/jjjjjjjj.jjj/kkkkkkkk.kkk/llllllll.lll/mmmmmmmm.mmm/nnnnnnnn.nnn/oooooooo.ooo/pppppppp.ppp/qqqqqqqq.qqq/rrrrrrrr.rrr/ssssssss.sss/tttttttt.ttt/uuuuuuuu.uuu/vvvvvvvv.vvv/wwwwwwww.www/a.pb.h
    /c/tmp/proto/aaaaaaaa.aaa/bbbbbbbb.bbb/cccccccc.ccc/dddddddd.ddd/eeeeeeee.eee/ffffffff.fff/gggggggg.ggg/hhhhhhhh.hhh/iiiiiiii.iii/jjjjjjjj.jjj/kkkkkkkk.kkk/llllllll.lll/mmmmmmmm.mmm/nnnnnnnn.nnn/oooooooo.ooo/pppppppp.ppp/qqqqqqqq.qqq/rrrrrrrr.rrr/ssssssss.sss/tttttttt.ttt/uuuuuuuu.uuu/vvvvvvvv.vvv/wwwwwwww.www/b.pb.h
    ```

**Comment by Igneous01** [comment]
any updates? Will the fix be merged in at some point?

**Comment by liyangyang13** [comment]
I encountered this problem recently, but unfortunately, this bug is still not fixed in the recent release of Protobuf.
The easiest way to solve this instead of manually fixing is to download the old version protoc-3.4.0-win32[https://github.com/protocolbuffers/protobuf/releases?after=v3.4.1](here) and then following the usual steps. It worked for me.

**Comment by OsamaNaeem1995** [comment]
> Thanks 😘 @apacha
> This my solution:
> 
> Head to the [protoc releases page](https://github.com/google/protobuf/releases) and download the protoc-3.4.0-win32.zip, extract it, and you will find protoc.exe in the bin directory.
> 
> Move this to models/research folder clone to local [tensorflow model project](https://github.com/tensorflow/models/)
> 
> Next,you can use the protoc command like
> 
> ```
> protoc object_detection/protos/*.proto --python_out=.
> ```
> [Reference linking](https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/)

i'm still getting the same error  , 
**no such file or directory **

> Thanks 😘 @apacha
> This my solution:
> 
> Head to the [protoc releases page](https://github.com/google/protobuf/releases) and download the protoc-3.4.0-win32.zip, extract it, and you will find protoc.exe in the bin directory.
> 
> Move this to models/research folder clone to local [tensorflow model project](https://github.com/tensorflow/models/)
> 
> Next,you can use the protoc command like
> 
> ```
> protoc object_detection/protos/*.proto --python_out=.
> ```
> [Reference linking](https://pythonprogramming.net/introduction-use-tensorflow-object-detection-api-tutorial/)

i am still getting the error despite following the steps you mentioned

**Comment by xycui** [comment]
Seems that it is keeping break since **3.5.0**. And this **regression bug** has already kept for almost 2 years.

**Comment by laszlocsomor** [comment]
@xycui : You're right. Sorry for the long time to fix. I'm not on the protobuf team so this was low priority for me.

**Comment by xycui** [comment]
@laszlocsomor Thank you so much for the help. But it seems that the fixing PR is still pending because of the 'release tag' missing.

**Comment by laszlocsomor** [comment]
You're welcome. I asked the reviewer to add it.

**Comment by apacha** [comment]
Halleluja!

**Comment by JamesOldfield** [comment]
Just for the record: this fix was first released in protobuf 3.10. I haven't properly checked but the commit 5b6238e can be found in the 3.10.x branch.
