### ISSUE TITLE
[PHP] Fatal error: Given value is not message.

### ISSUE THREAD

**Issue by jhaboush** [protocolbuffers/protobuf#5581]
**What version of protobuf and what language are you using?**
Version: 3.6.1
Language: PHP

**What operating system (Linux, Windows, ...) and version?**
Linux Ubuntu 16.04.5 LTS. Kernel: 4.15.0-43
**What runtime / compiler are you using (e.g., python version or gcc version)**
php extension compiled with gcc 5.4.0
**What did you do?**
I'm trying to use google/cloud-datastore package. The package suggests ext-grpc & ext-protobuf for better performance. I installed both from pecl, but with protobuf.so loaded, I consistently get:
`PHP Fatal error: Given value is not message. in vendor/google/cloud-datastore/src/V1/LookupRequest.php on line 129`. Please note that when disabling protobuf.so extension, the error disappears and code works as expected.
1. composer require "google/cloud-datastore:1.6.0"
2. run the following snippet:
```php

require_once __DIR__ . '/vendor/autoload.php';
// Intialize Datastore client with valid credentials.
$dataStoreClient = new \Google\Cloud\Datastore\DatastoreClient();
// Get Datastore entity key
$key = $dataStoreClient->key('<kind>', '<entity-id-value>');

// This call here produces: "Fatal error: Given value is not message."
$dataStoreClient->lookup($key);
```
**What did you expect to see**
Code works as is the case when google/protobuf package is used instead of c extension

**What did you see instead?**
PHP Fatal error: Given value is not message. in vendor/google/cloud-datastore/src/V1/LookupRequest.php on line 129
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by TeBoring** [comment]
Could you dig a little further to reproduce the bug of protobuf?
I am not familiar with Datastore. It's hard for me to figure out the problem.

**Comment by jhaboush** [comment]
I fear I'm not able to help with more details. When protobuf.so is loaded, php debugger isn't very helpful. but I'll still post what I got, in hope you find it useful.

PHP Stack trace:
```
1. {main}() /home/jad/tmp_repo/protobuf-datastore/test.php:0
2. Google\Cloud\Datastore\DatastoreClient->lookup($key = *uninitialized*, $options = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/test.php:11
3. Google\Cloud\Datastore\DatastoreClient->lookupBatch($keys = *uninitialized*, $options = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-datastore/src/DatastoreClient.php:911
4. Google\Cloud\Datastore\Operation->lookup($keys = *uninitialized*, $options = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-datastore/src/DatastoreClient.php:963
5. Google\Cloud\Datastore\Connection\Grpc->lookup($args = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-datastore/src/Operation.php:367
6. Google\Cloud\Datastore\Connection\Grpc->send($request = *uninitialized*, $args = *uninitialized*, $whitelisted = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-datastore/src/Connection/Grpc.php:184
7. Google\Cloud\Core\GrpcRequestWrapper->send($request = *uninitialized*, $args = *uninitialized*, $options = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-core/src/GrpcTrait.php:82
8. Google\Cloud\Core\ExponentialBackoff->execute($function = *uninitialized*, $arguments = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-core/src/GrpcRequestWrapper.php:149
9. call_user_func_array:{/home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-core/src/ExponentialBackoff.php:74}(*uninitialized*, *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-core/src/ExponentialBackoff.php:74
10. Google\Cloud\Datastore\V1\DatastoreClient->lookup($projectId = *uninitialized*, $keys = *uninitialized*, $optionalArgs = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-core/src/ExponentialBackoff.php:74
11. Google\Cloud\Datastore\V1\LookupRequest->setKeys($var = *uninitialized*) /home/jad/tmp_repo/protobuf-datastore/vendor/google/cloud-datastore/src/V1/Gapic/DatastoreGapicClient.php:230
```

The php method where this is triggered (LookupRequest::setKeys) receives the same type argument in both cases (ext-protobuf & google/protobuf package), an instance of `Google\Cloud\Datastore\V1\Key` which extends `Google\Protobuf\Internal\Message`. 
I noticed in the case of having protobuf.so loaded that this value is set as it and this triggers the error. When using php protobuf package, the value is transformed into `Google\Protobuf\Internal\RepeatedField` and that works.

**Comment by dwsupplee** [comment]
@jhaboush I've opened https://github.com/googleapis/google-cloud-php/issues/1599 to investigate this a bit further. If we determine the issue isn't related to the client library but instead may be related to protobuf, we can circle back here :).

**Comment by jdpedrie** [comment]
The issue seems to be related to modification of values by reference prior to passing them into the Protobuf message.

Simplifying the code in Google Cloud PHP which triggers the error, I can demonstrate the distinction:

```php
use Google\ApiCore\Serializer;
use Google\Cloud\Datastore\V1\Key;
use Google\Cloud\Datastore\V1\LookupRequest;

$s = new Serializer;
foreach ($keys as &$key) {
    $key = $s->decodeMessage(new Key, $key);
}

$request = new LookupRequest;
$request->setKeys($keys); // Fatal Error: Given value is not message.
```

Whereas, if we do not modify `$keys` by reference, the error does not occur:

```php
use Google\ApiCore\Serializer;
use Google\Cloud\Datastore\V1\Key;
use Google\Cloud\Datastore\V1\LookupRequest;

$s = new Serializer;
$res = [];
foreach ($keys as $key) {
    $res[] = $s->decodeMessage(new Key, $key);
}

$request = new LookupRequest;
$request->setKeys($res);
```

The same outcome repeats itself in other cases which do not use the GAX serializer. I've demonstrated several of them in [this gist](https://gist.github.com/jdpedrie/555d9ea18ffca5d1fd45e78f0346430a).

**Comment by TeBoring** [comment]
What doe decode message return?

**Comment by TeBoring** [comment]
decodeMessage

**Comment by jdpedrie** [comment]
It returns its first argument, populated with the data provided in the second argument.

For instance:

```php
$val = $serializer->decodeMessage(new Foo, ['hello' => 'world']);
var_dump($val instanceof Foo); // true
echo $val->getHello(); // world
```

**Comment by TeBoring** [comment]
@jdpedrie are you able to write an example to reproduce the bug? How shall I implement the decodeMessage to reproduce the bug?
BTW, we support array constructor. Why don't they simply do ```new Foo(['hello' => 'world'])```

**Comment by TeBoring** [comment]
I see. The problem is that c extension currently require messages in array to be object instead of reference.
Could datastore use object in array for now?

**Comment by TeBoring** [comment]
The problem is the array constructor of message previously also expect all values are not reference.
I have another fix in the change. Please take another look.

**Comment by jdpedrie** [comment]
Confirmed that the latest change in the PR fixes this array constructor as well. Thanks for your attention to this! :)

**Comment by TeBoring** [comment]
@jdpedrie, could you help me review that change?

**Comment by TeBoring** [comment]
Is https://github.com/protocolbuffers/protobuf/issues/5091 also fixed by this change?

**Comment by jdpedrie** [comment]
#5091 is still failing with the extension compiled from your pull request.
