### ISSUE TITLE
Fatal error: Generated message class Picture\PictureResponse hasn't been defined in /home//tlt/grpc_test/GPBMetadata/Picture.php on line 28

### ISSUE THREAD

**Issue by tangleiao** [protocolbuffers/protobuf#5917]
I have used command ,  generate php codes
protoc --proto_path=./protos/ --php_out=./ --grpc_out=./ --plugin=protoc-gen-grpc=/usr/local/bin/grpc_php_plugin ./protos/picture.proto

IDL 
syntax = "proto3";

package picture;

service Picture {
    rpc getPicturesByIds(PictureRequest) returns (PictureResponse) {}
}

message PictureRequest {
    repeated int32 Ids = 1;
}

message PictureResponse {
    repeated Pic picList = 1;
    string err = 2;
}

message Pic{
    int64  picid = 1;
    string desc = 5;
}

**Comment by TeBoring** [comment]
Can you try 3.7.x branch? We have some fixes for that.

**Comment by tangleiao** [comment]
@TeBoring I have update to 3.7.0， but the same error， it is not work.

**Comment by TeBoring** [comment]
We have fixed in 3.7.x branch, not 3.7.0 release. Could you try build the
extension with the 3.7.x branch?

**Comment by tangleiao** [comment]
@ TeBoring 
Cloning and installing version 3.7.x is still the same error

**Comment by TeBoring** [comment]
Could you also paste your php code and composer setup? And are you using
php implementation or c extension? Which php version are you using?

**Comment by TeBoring** [comment]
Besides, does your code work with early version of protobuf? Or this is your first time using php protobuf?

**Comment by tangleiao** [comment]
it is my first time using php protobuf,  php version 7.2.4 , I am using php extenstion grpc.so (1.19.0)and protobuf.so (3.7.0)
composer.json
{
  "name": "grpc/grpc-demo",
  "description": "gRPC example for PHP",
  "require": {
    "grpc/grpc": "^v1.19.0",
    "google/protobuf": "^v3.7.0"
  },
  "autoload": {
    "psr-4": {
      "": "route_guide/"
    }
  }
}

**Comment by tangleiao** [comment]
@TeBoring   Can I have your email?  I will send my codes to your email.

**Comment by TeBoring** [comment]
You can paste code here. It redirects to my email.

**Comment by tangleiao** [comment]
@TeBoring 
This is my codes, can you help me?
[test.zip](https://github.com/protocolbuffers/protobuf/files/2999069/test.zip)

**Comment by TeBoring** [comment]
Could you uninstall protobuf c extension and run your code again?

**Comment by tangleiao** [comment]
I uninstall protobuf.so,  still eror
Fatal error: Uncaught Error: Call to a member function getPicList() on null

**Comment by tangleiao** [comment]
@TeBoring 
I install protobuf in other server , error :
PHP Fatal error:  Generated message class Picture\Pic hasn't been defined in /home/centos/test/GPBMetadata/Picture.php on line 28

**Comment by TeBoring** [comment]
Where is generated code put? Have you set up composer.json properly to
autoload generated files?

**Comment by tangleiao** [comment]
@TeBoring 
I install protobuf 3.7.1 , the attachment is code：
[test.zip](https://github.com/protocolbuffers/protobuf/files/3016827/test.zip)

**Comment by tangleiao** [comment]
@TeBoring
Do you give me some suggestion

**Comment by neerajchandel1985** [comment]
@TeBoring, @tangleiao, I have installed <protobuf-php-3.10.1.zip> to generate the PHP class from the proto file and getting the bellow error. Please help out with me.

**PHP Fatal error:  Generated message class InterfaceProto hasn't been defined (InterfaceProto, (null), (null), (null))**
