### ISSUE TITLE
master/ Fedora 32 / gcc10 FAIL with -Werror=type-limits in google/protobuf/map_lite_unittest.pb.cc

### ISSUE THREAD

**Issue by dimhen** [protocolbuffers/protobuf#7514]
protobuf
commit 2ae7cf0e03c3469973e592e812565e4ee2470e0b (HEAD -> master, origin/master, origin/HEAD)

Fedora 32 / x86_64
gcc version 10.1.1 20200507 (Red Hat 10.1.1-1) (GCC) 

git pull
./autogen.sh
./configure --prefix=/usr/local/protobuf
make -j2
V=1 make check
[...]
g++ -DHAVE_CONFIG_H -I. -I..    -pthread -DHAVE_PTHREAD=1 -DHAVE_ZLIB=1 -Wall -Wextra -Werror -Wno-unused-parameter -g -std=c++11 -DNDEBUG -MT google/protobuf/no_warning_test-map_lite_unittest.pb.o -MD -MP -MF google/protobuf/.deps/no_warning_test-map_lite_unittest.pb.Tpo -c -o google/protobuf/no_warning_test-map_lite_unittest.pb.o `test -f 'google/protobuf/map_lite_unittest.pb.cc' || echo './'`google/protobuf/map_lite_unittest.pb.cc
In file included from ./google/protobuf/map_type_handler.h:34,
                 from ./google/protobuf/map.h:51,
                 from ./google/protobuf/generated_message_table_driven.h:34,
                 from ./google/protobuf/map_lite_unittest.pb.h:26,
                 from google/protobuf/map_lite_unittest.pb.cc:4:
./google/protobuf/parse_context.h: In instantiation of 'bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 130]':
google/protobuf/map_lite_unittest.pb.cc:1593:73:   required from here
./google/protobuf/parse_context.h:398:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  398 |     return *ptr == tag;
      |            ~~~~~^~~~~~
./google/protobuf/parse_context.h: In instantiation of 'bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 138]':
google/protobuf/map_lite_unittest.pb.cc:1605:73:   required from here
./google/protobuf/parse_context.h:398:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
./google/protobuf/parse_context.h: In instantiation of 'bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 146]':
google/protobuf/map_lite_unittest.pb.cc:1617:73:   required from here
./google/protobuf/parse_context.h:398:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
./google/protobuf/parse_context.h: In instantiation of 'bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 810]':
google/protobuf/map_lite_unittest.pb.cc:4074:73:   required from here
./google/protobuf/parse_context.h:398:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
./google/protobuf/parse_context.h: In instantiation of 'bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 818]':
google/protobuf/map_lite_unittest.pb.cc:4087:73:   required from here
./google/protobuf/parse_context.h:398:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:4403: google/protobuf/no_warning_test-map_lite_unittest.pb.o] Error 1
make[2]: Leaving directory '/tmp/protobuf/src'
make[1]: *** [Makefile:8191: check-am] Error 2
make[1]: Leaving directory '/tmp/protobuf/src'
make: *** [Makefile:1849: check-recursive] Error 1

**Comment by gerben-s** [comment]
I feel this is more a "compiler bug" then an issue in our code. gcc is issuing a warning the code actively protects itself from.

**Comment by gerben-s** [comment]
Here is a small reproduction

https://godbolt.org/z/F9vtCd

If code explicitely checks a case cannot occur then a warning in dead code is IMO a compiler bug in the warnings.

**Comment by dimhen** [comment]
Thank you for clarification!

FYI: there are already bug report https://gcc.gnu.org/PR95148

**Comment by davidlt** [comment]
I got this error too on Fedora 33 (Rawhide) on riscv64 while compiling 3.11.4 release.

```
[..]
./google/protobuf/parse_context.h:397:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  397 |     return *ptr == tag;
      |            ~~~~~^~~~~~
[..]
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:4475: google/protobuf/no_warning_test-unittest_lite.pb.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:4461: google/protobuf/no_warning_test-map_lite_unittest.pb.o] Error 1
cc1plus: all warnings being treated as errors
make[2]: *** [Makefile:4573: google/protobuf/no_warning_test-map_proto2_unittest.pb.o] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/protobuf-3.11.4/src'
```

**Comment by Romain-Geissler-1A** [comment]
Hi,

@gerben-s Technically this warning can be avoided by using compile time "if": `if constexpr (tag < 128) {`

I checked on Compiler Explorer and that works (ie the warning goes away with recent gcc). `if constexpr` is C++17 only, and I know Protobuf right now requires C++11, but can we consider using "if constexpr" conditionally when  the feature macro `__cpp_if_constexpr` is defined ? Note that gcc 11 enables C++17 by default, I also expect LLVM to follow on that path soon as well.

Cheers,
Romain

**Comment by Romain-Geissler-1A** [comment]
Note: this issue is fixed in Protobuf >= 3.15.0 thanks to PR #8092.

**Comment by nmaludy** [comment]
@Romain-Geissler-1A i can confirm i'm still seeing this with `3.15.5` on CentOS 8 with gcc 10.2.0

**Comment by Romain-Geissler-1A** [comment]
@nmaludy This is not this issue, but PR8309 which was merged already (I don't know in which version of Protobuf though).

**Comment by nmaludy** [comment]
@Romain-Geissler-1A Sorry for the confusion! Thanks for the fix!

**Comment by elharo** [comment]
so this is fixed?
