### ISSUE TITLE
"Map fields are not allowed in oneofs"

### ISSUE THREAD

**Issue by jkopczyn** [protocolbuffers/protobuf#7542]
**What version of protobuf and what language are you using?**
Version: libprotoc 3.6.1  (proto3 syntax explicitly set in the source)
Language: Go

**What operating system (Linux, Windows, ...) and version?**
Linux, specifically gLinux Rodete

**What runtime / compiler are you using (e.g., python version or gcc version)**
I don't think that's a meaningful question here.

**What did you do?**
```
syntax = "proto3";

package foo;

message Step {

  oneof args_spec {
    map<string, string> arbitrary_args = 3;

    Empty empty_args = 4;
  }
}

message Empty {}
```
`$ protoc foo.proto --go_out=.`

**What did you expect to see**
["You can add fields of any type, but cannot use repeated fields."](https://developers.google.com/protocol-buffers/docs/proto3#using-oneof), so I expected to get a `foo.pb.go` file.

**What did you see instead?**
`foo.proto:8:8: Map fields are not allowed in oneofs.`

**Anything else we should know about your project / environment**
I'm using the Chrome infrastructure package manager, CIPD, to install protoc. That's probably not relevant, but might be.

**Comment by jkopczyn** [comment]
It has been brought to my attention elsewhere that this is because maps are represented as repeated fields internally. Recommendation: change the error message to
```
Maps are considered a repeated fields, which are not allowed in oneofs.
```
I am also filing a PR with the doc maintainers to make this clearer in the docs. Belt and suspenders.

**Comment by znkr** [comment]
Removing the go label, as this is not specific to go but a general limitation of the protobuf language.

**Comment by esrauchg** [comment]
I double checked error message in this case is currently "Map fields are not allowed in oneofs", so this issue must have been fixed some time in the past 5 years.

**Comment by jkopczyn** [comment]
No, @esrauchg, that's proof the issue is still unsolved. Please reopen.

**Comment by esrauchg** [comment]
Ah sorry, I misunderstood.

The documentation has also been updated correspondingly:  https://protobuf.dev/programming-guides/proto3/#using-oneof "You can add fields of any type, except map fields and repeated fields."

Map and repeated fields never have explicit presence (never have 'hassers'), somewhat as an implication/restriction of the wire format. Only fields with presence can be in oneofs (the semantic is actually 'these fields all behave the same as if they were top level, but any time any one of these would be assigned to, automatically clear all of the rest).

Unfortunately we don't plan to add support for explicit presence map fields, which in turn means we can't support them in oneofs. If you need a oneof with a map in it, the workaround is to box it up in a message and use that message as the field in the oneof.

**Comment by jkopczyn** [comment]
Well, the error message still needs to be fixed.

**Comment by esrauchg** [comment]
Do you mean you suggest it include the workaround in the error message?

**Comment by jkopczyn** [comment]
Many improvements are possible. I previously suggested

> `Maps are considered repeated fields, which are not allowed in oneofs.`

and still consider this adequate. `Maps and repeated fields are not allowed in oneofs.` would be fine too.

What is not fine, is giving an error message which is nonsensical unless you know implementation details that ought to be irrelevant. A new user in the last five years who puts a map in a oneof gets a message telling them it failed because of a repeated field, when as far as they can tell no such thing is present. That's unacceptable.

**Comment by esrauchg** [comment]
>  A new user in the last five years who puts a map in a oneof gets a message telling them it failed because of a repeated field, when as far as they can tell no such thing is present.

If you can point me to the message that tell users a map field failed because of a repeated field then I can try to correct that. 

It does look like the original issue report correctly pointed out the documentation was wrong, because it did mentioned that repeated field weren't allowed but failed to mention that map fields also aren't allowed, but it looks like that was fixed so that it now mentions that neither maps nor repeated field are allowed in oneofs.

> What is not fine, is giving an error message which is nonsensical unless you know implementation details that ought to be irrelevant

I agree that we don't/shouldn't expect most users to know that.

So the error message should just tell them that maps aren't allowed in onesofs (if they try to do that), and say that repeated fields are not allowed in oneofs (if they try to do that). The technical reason for why those two types happen to be the same as eachother is only a curiosity, the relevant part is only that they aren't allowed in that context.

Today it looks like the error messages match my expectations though:
```
oneof xyz {
    repeated int32 x = 1;
  }
```

Gives the error: "Fields in oneofs must not have labels (required / optional / repeated)."

```
oneof xyz {
    map<int32, int32> x = 1;
  }
```

Gives the error: "Map fields are not allowed in oneofs."
