### ISSUE TITLE
[Java] Cannot use `class` as field name.

### ISSUE THREAD

**Issue by dpdani** [protocolbuffers/protobuf#9999]
Protobuf allows `class` as a field name, but since `class` is a reserved reserved in Java, protobuf changes the field's name to `class_`, but this doesn't allow for a generated class to e.g. be printed.

To reproduce:

```proto
syntax = "proto3";
package tests;
option java_multiple_files = true;
option java_package = "org.example.proto";
message MyTest {
  optional string class = 1;
}
```

```java
package org.example;
import org.example.proto.MyTest;
public class Tester {
    public static void main(String[] args) {
        MyTest myTest = MyTest.newBuilder()
                .setClass_("test-class")
                .build();
        System.out.println("myTest.getClass_() = " + myTest.getClass_());
        System.out.println("myTest = " + myTest);
    }
}
```

Running it, shows this error:

```
16:57:21: Executing ':Tester.main()'...

> Task :extractIncludeProto UP-TO-DATE
> Task :extractProto UP-TO-DATE
> Task :generateProto UP-TO-DATE
> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes

> Task :Tester.main() FAILED
myTest.getClass_() = test-class

6 actionable tasks: 2 executed, 4 up-to-date
Exception in thread "main" java.lang.RuntimeException: Generated message class "org.example.proto.MyTest$Builder" missing method "clearClass".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$OneofAccessor.<init>(GeneratedMessageV3.java:2076)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1990)
	at org.example.proto.MyTest.internalGetFieldAccessorTable(MyTest.java:87)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:349)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:339)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:606)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.example.Tester.main(Tester.java:9)
Caused by: java.lang.NoSuchMethodException: org.example.proto.MyTest$Builder.clearClass()
	at java.lang.Class.getMethod(Class.java:1814)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
	... 12 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Tester.main()'.
> Process 'command '/.../.jdks/corretto-1.8.0_332/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 259ms
16:57:22: Execution finished ':Tester.main()'.
```

Notice that the method named `clearClass_` exists, instead of `clearClass`.
I think this is a bug, but if I'm doing something wrong, please let me know. Any help would be appreciated :pray: 

---
Protoc Version: 3.15.8 (through [gradle plugin](https://github.com/google/protobuf-gradle-plugin), version 0.8.18)
Runtime Version: 3.15.8 (also tested with 3.20.1)
OS: Ubuntu 21.10

**Comment by elharo** [comment]
Looks like someone (probably me) forgot to name mangle clearClass

**Comment by elharo** [comment]
I think this is fixed in later versions of protobuf. Can you try upgrading to 3.20.1 and report the results? Thanks.

**Comment by elharo** [comment]
You'll need to compile with protoc 3.20.1 and use that as your runtime. Upgrading the runtime alone is probably not enough.

**Comment by dpdani** [comment]
Updated both runtime and protoc to 3.20.1, but still getting the same issue:

```
11:04:37: Executing ':Tester.main()'...

> Task :extractIncludeProto
> Task :extractProto
> Task :generateProto
> Task :compileJava
> Task :processResources
> Task :classes

> Task :Tester.main() FAILED
myTest.getClass_() = test-class

6 actionable tasks: 6 executed
Exception in thread "main" java.lang.RuntimeException: Generated message class "org.example.proto.MyTest$Builder" missing method "clearClass".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1847)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$OneofAccessor.<init>(GeneratedMessageV3.java:2076)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:1990)
	at org.example.proto.MyTest.internalGetFieldAccessorTable(MyTest.java:89)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:364)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:354)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:619)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.example.Tester.main(Tester.java:9)
Caused by: java.lang.NoSuchMethodException: org.example.proto.MyTest$Builder.clearClass()
	at java.lang.Class.getMethod(Class.java:1814)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1844)
	... 12 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Tester.main()'.
> Process 'command '/home/dp/.jdks/corretto-1.8.0_332/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 287ms
11:04:37: Execution finished ':Tester.main()'.
```

**Comment by elharo** [comment]
I am unable to reproduce this at head in google3. The below test passes for me. There could perhaps be something different in the open source release. If you can send a PR that includes  a failing unit test, I'll look again. 


```
  @Test
  // https://github.com/protocolbuffers/protobuf/issues/9999
  public void testNameMangleClass() {
     Proto3SpecialFieldName myTest = Proto3SpecialFieldName.newBuilder()
                .setClass_("test-class")
                .build();
     assertThat(myTest.getClass_()).isEqualTo("test-class");
     assertThat(myTest.toString()).isEqualTo("test-class");
  }
```
